//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursova_Aleksandar.PIServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PIServiceReference.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectUser", ReplyAction="*")]
        Kursova_Aleksandar.PIServiceReference.SelectUserResponse SelectUser(Kursova_Aleksandar.PIServiceReference.SelectUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Kursova_Aleksandar.PIServiceReference.SelectUserResponse> SelectUserAsync(Kursova_Aleksandar.PIServiceReference.SelectUserRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterNewUsers", ReplyAction="*")]
        Kursova_Aleksandar.PIServiceReference.RegisterNewUsersResponse RegisterNewUsers(Kursova_Aleksandar.PIServiceReference.RegisterNewUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterNewUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<Kursova_Aleksandar.PIServiceReference.RegisterNewUsersResponse> RegisterNewUsersAsync(Kursova_Aleksandar.PIServiceReference.RegisterNewUsersRequest request);
        
        // CODEGEN: Generating message contract since element name number from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterNewVignette", ReplyAction="*")]
        Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteResponse RegisterNewVignette(Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterNewVignette", ReplyAction="*")]
        System.Threading.Tasks.Task<Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteResponse> RegisterNewVignetteAsync(Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteRequest request);
        
        // CODEGEN: Generating message contract since element name ShowAllDataResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllData", ReplyAction="*")]
        Kursova_Aleksandar.PIServiceReference.ShowAllDataResponse ShowAllData(Kursova_Aleksandar.PIServiceReference.ShowAllDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowAllData", ReplyAction="*")]
        System.Threading.Tasks.Task<Kursova_Aleksandar.PIServiceReference.ShowAllDataResponse> ShowAllDataAsync(Kursova_Aleksandar.PIServiceReference.ShowAllDataRequest request);
        
        // CODEGEN: Generating message contract since element name number from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectVignetteByCarNumber", ReplyAction="*")]
        Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberResponse SelectVignetteByCarNumber(Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectVignetteByCarNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberResponse> SelectVignetteByCarNumberAsync(Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectUser", Namespace="http://tempuri.org/", Order=0)]
        public Kursova_Aleksandar.PIServiceReference.SelectUserRequestBody Body;
        
        public SelectUserRequest() {
        }
        
        public SelectUserRequest(Kursova_Aleksandar.PIServiceReference.SelectUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public SelectUserRequestBody() {
        }
        
        public SelectUserRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kursova_Aleksandar.PIServiceReference.SelectUserResponseBody Body;
        
        public SelectUserResponse() {
        }
        
        public SelectUserResponse(Kursova_Aleksandar.PIServiceReference.SelectUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelectUserResult;
        
        public SelectUserResponseBody() {
        }
        
        public SelectUserResponseBody(string SelectUserResult) {
            this.SelectUserResult = SelectUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterNewUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterNewUsers", Namespace="http://tempuri.org/", Order=0)]
        public Kursova_Aleksandar.PIServiceReference.RegisterNewUsersRequestBody Body;
        
        public RegisterNewUsersRequest() {
        }
        
        public RegisterNewUsersRequest(Kursova_Aleksandar.PIServiceReference.RegisterNewUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterNewUsersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int right;
        
        public RegisterNewUsersRequestBody() {
        }
        
        public RegisterNewUsersRequestBody(string user, string pass, int right) {
            this.user = user;
            this.pass = pass;
            this.right = right;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterNewUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterNewUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kursova_Aleksandar.PIServiceReference.RegisterNewUsersResponseBody Body;
        
        public RegisterNewUsersResponse() {
        }
        
        public RegisterNewUsersResponse(Kursova_Aleksandar.PIServiceReference.RegisterNewUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterNewUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterNewUsersResult;
        
        public RegisterNewUsersResponseBody() {
        }
        
        public RegisterNewUsersResponseBody(string RegisterNewUsersResult) {
            this.RegisterNewUsersResult = RegisterNewUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterNewVignetteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterNewVignette", Namespace="http://tempuri.org/", Order=0)]
        public Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteRequestBody Body;
        
        public RegisterNewVignetteRequest() {
        }
        
        public RegisterNewVignetteRequest(Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterNewVignetteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string number;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cat;
        
        public RegisterNewVignetteRequestBody() {
        }
        
        public RegisterNewVignetteRequestBody(string number, string date, int cat) {
            this.number = number;
            this.date = date;
            this.cat = cat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterNewVignetteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterNewVignetteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteResponseBody Body;
        
        public RegisterNewVignetteResponse() {
        }
        
        public RegisterNewVignetteResponse(Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterNewVignetteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterNewVignetteResult;
        
        public RegisterNewVignetteResponseBody() {
        }
        
        public RegisterNewVignetteResponseBody(string RegisterNewVignetteResult) {
            this.RegisterNewVignetteResult = RegisterNewVignetteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowAllDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowAllData", Namespace="http://tempuri.org/", Order=0)]
        public Kursova_Aleksandar.PIServiceReference.ShowAllDataRequestBody Body;
        
        public ShowAllDataRequest() {
        }
        
        public ShowAllDataRequest(Kursova_Aleksandar.PIServiceReference.ShowAllDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowAllDataRequestBody {
        
        public ShowAllDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowAllDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowAllDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kursova_Aleksandar.PIServiceReference.ShowAllDataResponseBody Body;
        
        public ShowAllDataResponse() {
        }
        
        public ShowAllDataResponse(Kursova_Aleksandar.PIServiceReference.ShowAllDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowAllDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowAllDataResult;
        
        public ShowAllDataResponseBody() {
        }
        
        public ShowAllDataResponseBody(string ShowAllDataResult) {
            this.ShowAllDataResult = ShowAllDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectVignetteByCarNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectVignetteByCarNumber", Namespace="http://tempuri.org/", Order=0)]
        public Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberRequestBody Body;
        
        public SelectVignetteByCarNumberRequest() {
        }
        
        public SelectVignetteByCarNumberRequest(Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectVignetteByCarNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string number;
        
        public SelectVignetteByCarNumberRequestBody() {
        }
        
        public SelectVignetteByCarNumberRequestBody(string number) {
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectVignetteByCarNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectVignetteByCarNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberResponseBody Body;
        
        public SelectVignetteByCarNumberResponse() {
        }
        
        public SelectVignetteByCarNumberResponse(Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectVignetteByCarNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelectVignetteByCarNumberResult;
        
        public SelectVignetteByCarNumberResponseBody() {
        }
        
        public SelectVignetteByCarNumberResponseBody(string SelectVignetteByCarNumberResult) {
            this.SelectVignetteByCarNumberResult = SelectVignetteByCarNumberResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Kursova_Aleksandar.PIServiceReference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Kursova_Aleksandar.PIServiceReference.WebService1Soap>, Kursova_Aleksandar.PIServiceReference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kursova_Aleksandar.PIServiceReference.SelectUserResponse Kursova_Aleksandar.PIServiceReference.WebService1Soap.SelectUser(Kursova_Aleksandar.PIServiceReference.SelectUserRequest request) {
            return base.Channel.SelectUser(request);
        }
        
        public string SelectUser(string user, string pass) {
            Kursova_Aleksandar.PIServiceReference.SelectUserRequest inValue = new Kursova_Aleksandar.PIServiceReference.SelectUserRequest();
            inValue.Body = new Kursova_Aleksandar.PIServiceReference.SelectUserRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            Kursova_Aleksandar.PIServiceReference.SelectUserResponse retVal = ((Kursova_Aleksandar.PIServiceReference.WebService1Soap)(this)).SelectUser(inValue);
            return retVal.Body.SelectUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kursova_Aleksandar.PIServiceReference.SelectUserResponse> Kursova_Aleksandar.PIServiceReference.WebService1Soap.SelectUserAsync(Kursova_Aleksandar.PIServiceReference.SelectUserRequest request) {
            return base.Channel.SelectUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kursova_Aleksandar.PIServiceReference.SelectUserResponse> SelectUserAsync(string user, string pass) {
            Kursova_Aleksandar.PIServiceReference.SelectUserRequest inValue = new Kursova_Aleksandar.PIServiceReference.SelectUserRequest();
            inValue.Body = new Kursova_Aleksandar.PIServiceReference.SelectUserRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((Kursova_Aleksandar.PIServiceReference.WebService1Soap)(this)).SelectUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kursova_Aleksandar.PIServiceReference.RegisterNewUsersResponse Kursova_Aleksandar.PIServiceReference.WebService1Soap.RegisterNewUsers(Kursova_Aleksandar.PIServiceReference.RegisterNewUsersRequest request) {
            return base.Channel.RegisterNewUsers(request);
        }
        
        public string RegisterNewUsers(string user, string pass, int right) {
            Kursova_Aleksandar.PIServiceReference.RegisterNewUsersRequest inValue = new Kursova_Aleksandar.PIServiceReference.RegisterNewUsersRequest();
            inValue.Body = new Kursova_Aleksandar.PIServiceReference.RegisterNewUsersRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.right = right;
            Kursova_Aleksandar.PIServiceReference.RegisterNewUsersResponse retVal = ((Kursova_Aleksandar.PIServiceReference.WebService1Soap)(this)).RegisterNewUsers(inValue);
            return retVal.Body.RegisterNewUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kursova_Aleksandar.PIServiceReference.RegisterNewUsersResponse> Kursova_Aleksandar.PIServiceReference.WebService1Soap.RegisterNewUsersAsync(Kursova_Aleksandar.PIServiceReference.RegisterNewUsersRequest request) {
            return base.Channel.RegisterNewUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kursova_Aleksandar.PIServiceReference.RegisterNewUsersResponse> RegisterNewUsersAsync(string user, string pass, int right) {
            Kursova_Aleksandar.PIServiceReference.RegisterNewUsersRequest inValue = new Kursova_Aleksandar.PIServiceReference.RegisterNewUsersRequest();
            inValue.Body = new Kursova_Aleksandar.PIServiceReference.RegisterNewUsersRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.right = right;
            return ((Kursova_Aleksandar.PIServiceReference.WebService1Soap)(this)).RegisterNewUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteResponse Kursova_Aleksandar.PIServiceReference.WebService1Soap.RegisterNewVignette(Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteRequest request) {
            return base.Channel.RegisterNewVignette(request);
        }
        
        public string RegisterNewVignette(string number, string date, int cat) {
            Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteRequest inValue = new Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteRequest();
            inValue.Body = new Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteRequestBody();
            inValue.Body.number = number;
            inValue.Body.date = date;
            inValue.Body.cat = cat;
            Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteResponse retVal = ((Kursova_Aleksandar.PIServiceReference.WebService1Soap)(this)).RegisterNewVignette(inValue);
            return retVal.Body.RegisterNewVignetteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteResponse> Kursova_Aleksandar.PIServiceReference.WebService1Soap.RegisterNewVignetteAsync(Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteRequest request) {
            return base.Channel.RegisterNewVignetteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteResponse> RegisterNewVignetteAsync(string number, string date, int cat) {
            Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteRequest inValue = new Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteRequest();
            inValue.Body = new Kursova_Aleksandar.PIServiceReference.RegisterNewVignetteRequestBody();
            inValue.Body.number = number;
            inValue.Body.date = date;
            inValue.Body.cat = cat;
            return ((Kursova_Aleksandar.PIServiceReference.WebService1Soap)(this)).RegisterNewVignetteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kursova_Aleksandar.PIServiceReference.ShowAllDataResponse Kursova_Aleksandar.PIServiceReference.WebService1Soap.ShowAllData(Kursova_Aleksandar.PIServiceReference.ShowAllDataRequest request) {
            return base.Channel.ShowAllData(request);
        }
        
        public string ShowAllData() {
            Kursova_Aleksandar.PIServiceReference.ShowAllDataRequest inValue = new Kursova_Aleksandar.PIServiceReference.ShowAllDataRequest();
            inValue.Body = new Kursova_Aleksandar.PIServiceReference.ShowAllDataRequestBody();
            Kursova_Aleksandar.PIServiceReference.ShowAllDataResponse retVal = ((Kursova_Aleksandar.PIServiceReference.WebService1Soap)(this)).ShowAllData(inValue);
            return retVal.Body.ShowAllDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kursova_Aleksandar.PIServiceReference.ShowAllDataResponse> Kursova_Aleksandar.PIServiceReference.WebService1Soap.ShowAllDataAsync(Kursova_Aleksandar.PIServiceReference.ShowAllDataRequest request) {
            return base.Channel.ShowAllDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kursova_Aleksandar.PIServiceReference.ShowAllDataResponse> ShowAllDataAsync() {
            Kursova_Aleksandar.PIServiceReference.ShowAllDataRequest inValue = new Kursova_Aleksandar.PIServiceReference.ShowAllDataRequest();
            inValue.Body = new Kursova_Aleksandar.PIServiceReference.ShowAllDataRequestBody();
            return ((Kursova_Aleksandar.PIServiceReference.WebService1Soap)(this)).ShowAllDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberResponse Kursova_Aleksandar.PIServiceReference.WebService1Soap.SelectVignetteByCarNumber(Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberRequest request) {
            return base.Channel.SelectVignetteByCarNumber(request);
        }
        
        public string SelectVignetteByCarNumber(string number) {
            Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberRequest inValue = new Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberRequest();
            inValue.Body = new Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberRequestBody();
            inValue.Body.number = number;
            Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberResponse retVal = ((Kursova_Aleksandar.PIServiceReference.WebService1Soap)(this)).SelectVignetteByCarNumber(inValue);
            return retVal.Body.SelectVignetteByCarNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberResponse> Kursova_Aleksandar.PIServiceReference.WebService1Soap.SelectVignetteByCarNumberAsync(Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberRequest request) {
            return base.Channel.SelectVignetteByCarNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberResponse> SelectVignetteByCarNumberAsync(string number) {
            Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberRequest inValue = new Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberRequest();
            inValue.Body = new Kursova_Aleksandar.PIServiceReference.SelectVignetteByCarNumberRequestBody();
            inValue.Body.number = number;
            return ((Kursova_Aleksandar.PIServiceReference.WebService1Soap)(this)).SelectVignetteByCarNumberAsync(inValue);
        }
    }
}
